config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:create, :destroy, :new]
  resources :users, only: [:create, :new, :show]
  resources :bands do
    resources :albums, only: :new
  end
  resources :albums, except: [:index, :new] do
    resources :tracks, only: :new
  end
  resources :tracks, except: [:index, :new]
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  live       :boolean          not null
#  band_id    :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class Album < ActiveRecord::Base
  validates :name, :band_id, presence: true
  belongs_to :band
  has_many :tracks, dependent: :destroy
  attr_reader :albums

  def albums
    @albums = Album.all
  end



end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime
#  updated_at :datetime
#

class Band < ActiveRecord::Base
  validates :name, presence: true

  has_many :albums, dependent: :destroy

  has_many :tracks,
  through: :albums,
  source: :tracks

  def bands
    @bands = Band.all
  end
end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  lyrics     :text
#  album_id   :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class Track < ActiveRecord::Base
  validates :name, :album_id, presence: true

  belongs_to :album
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :text             not null
#  password_digest :text             not null
#  session_token   :text             not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
validates :email, :password_digest, presence: true
validates( :password, length: { minimum: 6, allow_nil: true } )

after_initialize :ensure_session_token

attr_reader :password

  def self.generate_session_token
    self.session_token = SecureRandom.urlsafe_base64(16)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return user if user && user.is_password?(password)
    nil
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def albums
    @albums = Album.all
  end

  def index
    @albums = albums
    render :index
  end

  def new
    @album = Album.new
    render :new
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    @album = Album.find(params[:id])
    if @album.update_attributes(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  private

  def album_params
    params.require(:album)
      .permit(:name, :live, :band_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :logged_in?

  def current_user
    return nil unless self.session[:session_token]
    @user = User.find_by(session_token: self.session[:session_token])
  end

  def logged_in?
    current_user != nil
  end

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token! if current_user
    session[:session_token] = nil
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def bands
    @bands = Band.all
  end
  
  def index
    @bands = bands
    render :index
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  private

  def band_params
    params.require(:band)
      .permit(:name, :id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
      )

    if user
      login!(user)
      redirect_to user_url(user.id)
    else
      flash.now[:errors] = ["sorry, no such user/password combo exists"]
      render :new
    end
  end

  def new
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController


  def index
    @tracks = Track.all
    render :index
  end

  def new
    @track = Track.new
    render :new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def update
    @track = Track.find(params[:id])
    if @track.update_attributes(track_params)
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :edit
    end
  end

  private

  def track_params
    params.require(:track)
      .permit(:name, :id, :lyrics, :album_id)
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to user_url(current_user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/edit.html.erb
<h1><center>Edit the Album Details for <%= @album.name %>!</h1>

  <%= render "shared/errors" %>
  <%= render "shared/album_form", album: @album %>

app/views/albums/index.html.erb
<h1>List of all albums!</h1>

<ul>
  <% @albums.each do |album| %>
    <li><%= link_to album.name, album_url(album) %></li>
  <% end %>
</ul>

<%= link_to "Store a new album", new_album_url %>

app/views/albums/new.html.erb
<h1><center>New album for <%= @band ||= "OOPS!!!" %></h1>

  <%= render "shared/errors" %>
  <%= render "shared/album_form", album: @album, band: @band %>

app/views/albums/show.html.erb
<h1><mark>Album: <%= @album.name %> by <%= Band.find_by(id: @album.band_id).name %> </h1>

tracks:<br>
<%= @album.tracks.each do |track| track.name + "\n" end.join %>


<center><h4><mark>links for:</h4><p>
<mark>
<a href="/albums/1/edit">edit this album</a> <br>
destroy this album<br>
show this band<br>
show the tracks on this album<br>
make another album by this band

app/views/bands/index.html.erb
<h1>List of all bands!!</h1>

<ul>
  <% @bands.each do |band| %>
    <li><%= link_to band.name, band_url(band) %></li>
  <% end %>
</ul>

<%= link_to "Store a new band", new_band_url %>

app/views/bands/new.html.erb
<h1><center><font color = "yellow">Store a new Band</h1>

<%= render "shared/errors" %>
<%= render "shared/band_form", band: @band %>

app/views/bands/show.html.erb
<h1>

albums:





links: <br>
edit <br>
delete band <br>
see all bands <br>
enter a new band <br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- <body style="background-image:url(http://previews.123rf.com/images/genotar/genotar1004/genotar100400036/6938519-Grunge-musical-background-Stock-Photo-music-sheet-background.jpg);"> -->
  <font color="red"><mark><b>
  <h3><%= current_user.email if current_user %></h3>
  <% submit_text = (current_user ?  'Logout' : 'Login')%>
  <% action = (current_user ? "/session": "/session/new" ) %>
    <% method = (current_user ? :delete : :get) %>
  <form action= "<%= action %>" method="post">

    <input type="hidden"
            name="authenticity_token"
           value="<%= form_authenticity_token %>">

    <input type="hidden" name="_method" value="<%= method %>">
    <input type="submit" value="<%= submit_text %>">
</form>

<%= yield %>

</body>
</html>

app/views/shared/_album_form.html.erb
<% action = (album.persisted? ? album_url(album) : "/albums") %>
<% method = (album.persisted? ? :patch : :post) %>


<body style="background-image:url( http://www.camfm.co.uk/media/shows/thumbs/Cambridge_Golden_Record.png );">

<form action="/albums" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <input type="hidden"
          name="authenticity_token"
         value="<%= form_authenticity_token %>" >


  <label for="name">Album Name</label>
  <input
    type="text"
    name="album[name]"
    id="name"
    value="<% album.name %>">
  <br>

   <label for="band_name">Band Name</label>
   <select name="album[band_id]" id="album_name">
     <option></option>
     <% Band.all.each do |band| %>
       <option
         <%= band.id == album.band_id ? "selected" : "" %>
         value="<%= album.band_id %>">
         <%= band.name %>
       </option>
     <% end %>
   </select>
   <br>


  Live in Concert?
  <input
    type="radio"
    name="album[live]"
    value="true"
    id="yes"
    <%= "checked" if album.live %>>
  <label for="yes">Yes, and what a concert!!</label>
  <input
    type="radio"
    name="album[live]"
    value="false"
    id="no"
    <%= "checked" unless album.live %>>
    <label for="no">No way, the mix is too good.</label>
  <br>

  <input type="submit" value="Save Album Info">
</form>

app/views/shared/_band_form.html.erb
<body style="background-image:url(
http://3.bp.blogspot.com/_XqPYCCkXYWA/THrMVnJgAEI/AAAAAAAAAUg/KYahCD2QI38/s1600/guster.jpg
);">
<form action="/bands" method="post">
  <input type="hidden"
          name="authenticity_token"
         value="<%= form_authenticity_token %>" >


  <label for="name"><mark>Band Name</label>
  <input
    type="text"
    name="band[name]"
    id="name"
    value="<%= band.name %>">
  <br>


  <input type="submit" value="Save Band">
</form>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>

app/views/shared/_form.html.erb
<form action="<%= path %>" method="post">
  <input type="hidden"
          name="authenticity_token"
         value="<%= form_authenticity_token %>" >


  <label for="email">Email</label>
  <input
    type="text"
    name="user[email]"
    id="email">
  <br>

  <label for="password">Password</label>
  <input
    type="password"
    name="user[password]"
    id="password" >
  <br>

  <input type="submit" value="<%= button_text %>">
</form>

app/views/tracks/_track_form.html.erb
<% action = (album.persisted? ? track_url(track) : "/tracks") %>
<% method = (album.persisted? ? :patch : :post) %>

<body style="background-image:url( http://thumbs.dreamstime.com/x/warped-piano-music-sheet-background-23627360.jpg );">

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <input type="hidden"
          name="authenticity_token"
         value="<%= form_authenticity_token %>" >

   <label for="album_name">Album</label>
   <select name="track[album_id]" id="album_name">
     <option></option>
     <% Album::albums.each do |album| %>
       <option
         <%= album.id == album_id ? "selected" : "" %>
         value="<%= album.name %>">
         <%= album.name.upcase %>
       </option>
     <% end %>
   </select>
   <br>

  <label for="name">Name</label>
  <input
    type="text"
    name="track[name]"
    id="name">
  <br>

  <label for="password">Lyrics</label>
  <input
    type="password"
    name="user[password]"
    id="password" >
  <br>

  <input type="submit" value="Save Track Info">
</form>

app/views/tracks/new.html.erb
<h1>Store a new Track</h1>

<%= render "shared/errors" %>
<%= render "track_form", track: @track %>

app/views/users/new.html.erb
<h1>Create a Profile</h1>

<%= render "shared/errors" %>
<%= render "shared/form", user: @user, button_text: "Create User!", path: "/users" %>

app/views/users/show.html.erb
<h1><center>User Homepage</h1>
<br><br><center>you have successfully logged in, congratulations.